name: web_project
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  # Splash Screen
  flutter_native_splash: ^2.4.0

  # Responsive Design
  flutter_screenutil: ^5.9.0
  # An SVG library for rendering painting
  flutter_svg: ^2.0.10+1

  # Dependency Injection
  get_it: ^7.7.0

  # To load and cache network images
  cached_network_image: ^3.3.1

  # To display animations
  lottie: ^3.1.0

  # State management
  flutter_bloc: ^8.1.5

  #FireBase
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.16.1

  #A package which simplifies the task of updating your Flutter app's launcher icon
  flutter_launcher_icons: "^0.13.1"

#  flutter_launcher_icons:
  #  android: "launcher_icon"
  #  ios: true
  #  image_path: "assets/images/app_icon.jpg"


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/svgs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
